### PR TITLE
feat(tracing): implement trace context propagation using the Opentracing api

### PR DESCRIPTION
**Pull request by Rio**
This PR enables context propagation using newly introduced functions while maintaining backwards compatibility:
- `SendTaskWithContext`
- `SendGroupWithContext`
- `SendChordWithContext`
- `SendChainWithContext`

Essentially what happens is that if one of these functions is called it will try to inject the trace context found in `context.Context` into the signature's headers before calling the original non-WithContext function. On the worker side an attempt is made to extract that context again and add it to the tasks context. All these actions will simply start a new span if no trace context is found. As an extra the trace span will be available in the called function's context if the registered function has `context.Context` as a first argument so the trace can travel on. To get a good view of what a user should enable to get the benefits of tracing check `example/machinery.go` and uncomment the jaeger code in `example/tracers/jaeger.go`. Below is a screenshot of the jaeger's ui after a run of the example. Note that I've disabled the long running task so the graph is prettier. There are also some screen shots of the tags captured by the spans.

What is missing is a bit more documentation in the readme and some tests that verify the traces are actually propagating.

screenshot from 2018-02-25 16-21-04
screenshot from 2018-02-25 16-22-05
screenshot from 2018-02-25 16-22-58

### CODE REVIEW

**Comment by Rio** [comment]
I've omitted the actually updated vendor directory as I wasn't sure what the policy is around it and it introduced quite a lot of diff...

**Comment by Rio** [comment]
So added the vendor folder so the tests would at least run but it's not really clear to me why it simply stopped running. Any help here would be appreciated.

**Comment by Rio** [comment]
Closing and reopening PR in an attempt to get travis to restart the job.

**Comment by Rio** [comment]
go travis go!

**Comment by RichardKnop** [comment]
@Rio Thanks. This is great!

**Comment by Rio** [comment]
Any time!

**Comment by Rio** [comment]
Any idea what you need for a new release cut? Then I can switch out our internal fork back to upstream. Regarding coverage, I'm planning of increasing it at least for the new code I introduced but it'll come gradually as we integrate this further in our backend.

**Comment by Rio** [comment]
Ignore that, it's ready when it's ready :P

**Comment by seonixx** [comment]
@Rio thanks for this!

**Pull request merged**
