### PR TITLE
Implements AWS DynamoDB as Result Backend option

### PR DESCRIPTION
**Pull request by mjetpax**
This PR adds AWS DynamoDB as an optional result backend for machinery. Please find addiitonal information in the readme file and in instructions-notes.

### CODE REVIEW

**Comment by RichardKnop** [comment]
@mjetpax Thanks for this PR. Could you rebase against master (I have merged couple of PRs since this was created).

Also make sure to add the AWS DynamoDB dependencies to vendor folder? Something like:

`dep ensure -add github.com/aws/aws-sdk-go/service/dynamodb` should make the CI pass?

**Comment by ZhenhangTung** [comment]
Sure! I'm working on it.
I think there is one key point we need to discuss in this PR, which is ```CreatedAt``` being introduced. Check: https://github.com/RichardKnop/machinery/pull/239/files#diff-aaae9e6274d067f485799ecfc4cdc75aR37
From my perspective, I think this could help users to debug and trace job's history better.

**Comment by ZhenhangTung** [comment]
@RichardKnop Could you rebuild our latest build in TravisCI, for we don't have the write access. Seems like there is a timeout error. Thanks!

**Comment by RichardKnop** [comment]
@ZhenhangTung Ok will try to restart the build

**Pull request merged**
