### PR TITLE
Hotfix/gkarr/redis broker timer

### PR DESCRIPTION
**Pull request by georgekarrv**
@RichardKnop previous fix I added would create a for loop that would chew up cpu. added a timer.

### CODE REVIEW

**Comment by RichardKnop** [comment]
Merged 👍

**Comment by RichardKnop** [comment]
Just one more thing I noticed. Doesn't it need to be?

```go
				if concurrency == 0 || (len(pool)-len(deliveries) > 0) {
					task, err := b.nextTask(b.cnf.DefaultQueue)
					if err != nil {
						timer.Reset(time.Second)
						continue
					}

					deliveries <- task
				} else {
				        timer.Reset(time.Second)
				}
```

instead? Otherwise concurrency would not work properly (e.g. if we set concurrency to 4, it would take 4 seconds to start processing 4 parallel tasks). If we add the `else` clause, it will start processing tasks immediately until we reach the concurrency limit and then wait 1 sec.

What do you think?

**Comment by georgekarrv** [comment]
with that a 'successful' dequeu of a task where you push a task onto the deliveries channel would not reset the timer and you would never return to this select in the loop,

you could do this so long as on the line after deliveries you have another timer.Reset(time.Millisecond) or some such.

**Comment by RichardKnop** [comment]
Oh I see. I need to look at this closer when I have time. Perhaps using time.After would be an alternative. Just want to avoid slow picking up of new tasks when there are still parallel processing slots available.

**Comment by RichardKnop** [comment]
@georgekarrv See here. I think that's better: https://github.com/RichardKnop/machinery/pull/273

**Pull request merged**
