### PR TITLE
Fix issue #461: replace thrift.git using github repo

### PR DESCRIPTION
**Pull request by vincenthcui**
try to fix issue #461 

verify: `go mod download` and run as expected

### CODE REVIEW

**Comment by charleswhchan** [comment]
I wonder if the changes in `go.mod` should be:
```
replace (
	git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999 => github.com/apache/thrift v0.0.0-20180902110319-2566ecd5d999
	git.apache.org/thrift.git v0.0.0-20181218151757-9b75e4fe745a => github.com/apache/thrift v0.0.0-20181218151757-9b75e4fe745a
)
```

If you look at https://github.com/RichardKnop/machinery/blob/master/go.sum#L11, it is currently referencing git.apache.org/thrift.git in the following lines
```
git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999/go.mod h1:fPE2ZNJGynbRyZ4dJvy6G277gSllfV2HJqblrnkyeyg=
git.apache.org/thrift.git v0.0.0-20181218151757-9b75e4fe745a/go.mod h1:fPE2ZNJGynbRyZ4dJvy6G277gSllfV2HJqblrnkyeyg=
```

**Comment by vincenthcui** [comment]
> I wonder if the changes in `go.mod` should be:
> 
> ```
> replace (
> 	git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999 => github.com/apache/thrift v0.0.0-20180902110319-2566ecd5d999
> 	git.apache.org/thrift.git v0.0.0-20181218151757-9b75e4fe745a => github.com/apache/thrift v0.0.0-20181218151757-9b75e4fe745a
> )
> ```
> 
> If you look at https://github.com/RichardKnop/machinery/blob/master/go.sum#L11, it is currently referencing git.apache.org/thrift.git in the following lines
> 
> ```
> git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999/go.mod h1:fPE2ZNJGynbRyZ4dJvy6G277gSllfV2HJqblrnkyeyg=
> git.apache.org/thrift.git v0.0.0-20181218151757-9b75e4fe745a/go.mod h1:fPE2ZNJGynbRyZ4dJvy6G277gSllfV2HJqblrnkyeyg=
> ```

Once I run `go mod tidy`, the following lines are auto-removed by go mod tools, so I think replace one repo is enough.

By the way, maybe I show commit `go.sum` after `go mod tidy` run.

**Comment by charleswhchan** [comment]
@vincenthcui : Thanks for the explanation. Could you create a new PR with "go mod tidy". That would be great.

**Comment by vincenthcui** [comment]
@charleswhchan sure, I'm working on it with pleasure

**Pull request merged**
