### PR TITLE
refact factory

### PR DESCRIPTION
**Pull request by runner-mei**
refact BrokerFactory() and BackendFactory(), let it is  pluggability.

### CODE REVIEW

**Comment by cdelacruzpinto** [comment]
This merge request is super interesting, as it would reduce considerably build times. It would be great if this could be merged :-)

**Comment by RichardKnop** [comment]
@runner-mei There seem to be couple of conflicts. Could you fix those please?

**Comment by runner-mei** [comment]
I rebase it

**Comment by charleswhchan** [comment]
Is there an error at the end of the CI: https://travis-ci.org/RichardKnop/machinery/builds/565774213?utm_source=github_status&utm_medium=notification

```
machinery_sut | build github.com/RichardKnop/machinery/example: cannot load github.com/RichardKnop/machinery/v1/common/commonamqp: cannot find module providing package github.com/RichardKnop/machinery/v1/common/commonamqp
900machinery_sut | #go tool cover -html=coverage-all.out
901machinery_sut exited with code 0
902Aborting on container exit...
903Stopping machinery_sut_redis     ... 
904Stopping machinery_sut_gcppubsub ... 
905Stopping machinery_sut_memcached ... 
906Stopping machinery_sut_mongo     ... 
907Stopping machinery_sut_rabbitmq  ... 
908The command "make ci" exited with 0.
```

I did not see any test result when comparing the log with [1.6.7](https://travis-ci.org/RichardKnop/machinery/builds/557796478). 

This issue is affecting /master branch my PR #447 😃

**Comment by RichardKnop** [comment]
@vividvilla @charleswhchan reverted to before the broken pr merge.

**Pull request merged**
