### PR TITLE
Added DEBUG level

### PR DESCRIPTION
**Pull request by valeriano-manassero**
After https://github.com/RichardKnop/logging/pull/1
I think it's possible to add DEBUG level here.

I'm not sure this PR is ok so I'm asking for review and I will improve it if needed.

### CODE REVIEW

**Comment by valeriano-manassero** [comment]
@RichardKnop I have no clue on why Travis build is failing. Can you help me please?

**Comment by RichardKnop** [comment]
@valeriano-manassero can you rebase with the master branch? I have merged another PR today and it changed some things.

**Comment by valeriano-manassero** [comment]
Rebased and Dep updated.
It seems to me Dep update doesn't only update logging but also broke some dependency.

**Comment by valeriano-manassero** [comment]
@RichardKnop Since a `dep ensure` gives me errors, I tried to manually import the right file from logging and checks are now good.

I'm not sure this is good enough for you, waiting for your feedback.

**Pull request merged**
