### PR TITLE
Fix NewPool and Rewrite ParseRedisURL

### PR DESCRIPTION
**Pull request by duyanghao**
Fix `NewPool` Logic and Rewrite `ParseRedisURL` using `url.Parse`(It's probably more robust to just use url.Parse and extract all the info from the URL)

Signed-off-by: duyanghao <1294057873@qq.com>

### CODE REVIEW

**Comment by RichardKnop** [comment]
@duyanghao Can you rebase this against master? I have just merged another PR which changed how Redis URL is parsed.

**Comment by duyanghao** [comment]
@RichardKnop Done for Rebase.

**Comment by ZhenhangTung** [comment]
Please fix the errors thrown by ```make lint``` :) @duyanghao

**Comment by RichardKnop** [comment]
👍

**Pull request merged**
