### PR TITLE
ISSUE-232: prevent multiple chord triggers w/ concurrent workers

### PR DESCRIPTION
**Pull request by ItsLeeOwen**
- use findAndModify where lock is false to avoid update race conditions & simplify lock check
- use findAndModify in lockGroupMeta

### CODE REVIEW

**Comment by ItsLeeOwen** [comment]
@RichardKnop  trying to troubleshoot tests locally & on travis it's stalling and I'm not seeing why yet.

**Comment by ItsLeeOwen** [comment]
working on compatibility with redis/amqp

**Comment by ItsLeeOwen** [comment]
added sqs test suite

**Comment by ItsLeeOwen** [comment]
@RichardKnop   I haven't been able to track it down, but there is some condition where integration_tests can sometimes hang indefinitely.

**Comment by RichardKnop** [comment]
@ItsLeeOwen Yes, for some reason sometimes one of 2 builds during CI hangs. Probably related to docker somehow (I assume dependency containers like RabbitMQ/Redis don't start in correct order or something). I will need to try to debug that sometimes. It usually runs fine second time. So if one of builds is green and another one got stuck it very likely means it's ok. Bug in `make ci`.

**Pull request merged**
