### PR TITLE
Implements AWS SQS Broker Support

### PR DESCRIPTION
**Pull request by mjetpax**
This adds an AWS SQS broker implementation.

### CODE REVIEW

**Comment by RichardKnop** [comment]
Thanks for the PR! This will be quite hard for me to review as I haven't used Amazon SQS.

**Comment by RichardKnop** [comment]
There seems to be a conflict in `v1/brokers/broker.go`. Could you rebase?

**Comment by mjetpax** [comment]
Also, Amazon SQS is very user friendly, a couple of clicks and everything is all set up. The only gotcha is IAM permissions (if you're not already familiar with the AWS IAM).

**Comment by ZhenhangTung** [comment]
I believe the problems are these two:
1) Errors were thrown when running ```make lint```
2) Something went wrong when running tests in Go v1.9
I'm now taking care of these problems.

**Comment by ZhenhangTung** [comment]
On my local env, whose go version is ```go version go1.9.2 darwin/amd64```, but all tests pass. Maybe it's another reason or we could rerun CI after those errors are thrown by ```make lint``` being fixed.

**Comment by RichardKnop** [comment]
I will try checking out this branch locally and running tests.

**Comment by RichardKnop** [comment]
Yes the tests are passing. This seems like a linter / formatting issue. Merging this & will fix formatting in next commit.

**Comment by RichardKnop** [comment]
OK. Can you rebase against master? CI should be passing now.

**Comment by ZhenhangTung** [comment]
I've found a bug would sometimes break the tests. Another PR would be requested later, after @mjetpax  finish his review.
We appreciate your work and you really helped our team. @RichardKnop

**Pull request merged**
