### PR TITLE
It may be wrong for BrokerFactory to create a broker object only with…

### PR DESCRIPTION
**Pull request by KarlTango**
… checking the Config.backend.

### CODE REVIEW

**Comment by RichardKnop** [comment]
@KarlTango Can you explain this pull request in more detail?

I cannot merge this without understanding what's the purpose.

**Comment by regaw-leinad** [comment]
This is not a clean PR, especially with the addition of IDE metadata.

I agree there is an issue here, though.  Right now the code is checking the **_Backend_** config protocol to determine what **_Broker_** to create.  A better change here would be to change `cnf.ResultBackend` to `cnf.Broker`, since we still want to check for an `amqps` broker.

**Comment by KarlTango** [comment]
@regaw-leinad Thanks for your information.

**Comment by KarlTango** [comment]
@RichardKnop . As @regaw-leinad has said, right now the code is checking the Backend config protocol to determine what Broker to create . I just want to fix this bug simply. Now this bug  has been fixed by you. So it's OK now.

**Pull request closed without merging**
