### PR TITLE
add periodic task

### PR DESCRIPTION
**Pull request by KarlTango**
support periodic task

I add a distributed lock ensures that each scheduled task will only be published once. And the life cycle of a lock is the same as the schedule of a scheduled task

### CODE REVIEW

**Comment by iauglov** [comment]
We need it

**Review by RichardKnop — APPROVED** [review]

**Comment by RichardKnop** [comment]
@KarlTango Can you rebase with master branch please?

**Comment by RichardKnop** [comment]
There is some panic during integration tests :(

**Comment by KarlTango** [comment]
> There is some panic during integration tests :(

fixed

**Comment by mosasiru** [comment]
It seems that lock config changes to be must.
Is this intentional change? If so, the documentation may be better to be written.

https://github.com/RichardKnop/machinery/pull/534/files#diff-f86ce481fdf2697232c73fce1d2640ce1320cb5bd91d7b7e2b901d1bc8330332R236

**Comment by xmikasax** [comment]
@KarlTango can you please elaborate more about distributed lock, please? Do we need it only when scheduling same tasks from different processes?

**Comment by KarlTango** [comment]
> @KarlTango can you please elaborate more about distributed lock, please? Do we need it only when scheduling same tasks from different processes?

Yes. If you are running your app on multi machine as well as your app rely on machinery to manange its periodic task, then machinery need the distributed lock. Because it need to be guaranteed that the periodic task can and only can be run once at every schedule time.

**Comment by samuelololol** [comment]
@KarlTango how do I revoke or cancel a registered periodic task? Any hint?

**Comment by KostarevVI** [comment]
> > just remove the code of register periodic task

Can you elaborate on this please? It seems that cron task IDs are ignored, so I couldn't find a way to delete tasks that I set to be periodic.

**Pull request merged**
