### PR TITLE
Adding "Eager Mode"

### PR DESCRIPTION
**Pull request by mission-liao**
I came from python world, and there is a similar [project](https://github.com/celery/celery), which provides "always eager" mode for dev/test purpose, you can write your code, unit test your feature without preparing a environment.

Here is a draft implementation of that feature for this project, and welcome for any feedback.
Nothing special inside:
 - in-memory backend
 - by-pass broker

I borrowed the name "eager" from celery, do you guys have any better idea?

### CODE REVIEW

**Comment by mission-liao** [comment]
additional dependency: github.com/stretchr/testify

**Comment by mission-liao** [comment]
One issue found, the type assertion of TaskResult is not correct.

**Comment by RichardKnop** [comment]
Thanks.

Can you rebase against the latest code in the master branch?

I will take a look at this soonish.

**Comment by mission-liao** [comment]
Ok, I will open another one later, thanks.

**Pull request closed without merging**
