### PR TITLE
Backend mongo json changes

### PR DESCRIPTION
**Pull request by surendratiwari3**
mongodb changes travis ci build with added support for mongodb result value to be in json.now we can have json in the result set of result.

### CODE REVIEW

**Comment by surendratiwari3** [comment]
added support for mongodb result value to be in json

**Comment by surendratiwari3** [comment]
@codecov-io please let you know more in details.

**Comment by surendratiwari3** [comment]
@RichardKnop please merge this code as i tested this with load.this is required when someone want the result value should be inserted as json into mongodb for further processing. after changes i am able to insert as json into mongodb like this.
db.tasks.find({_id: "1505906984389049"} ).pretty()
{
	"_id" : "1505906984389049",
	"state" : "SUCCESS",
	"results" : [
		{
			"value" : {
				"FreeSWITCH-Hostname" : "ip-172-31-29-181",
				"FreeSWITCH-Switchname" : "ip-172-31-29-181",
				"Up-Time" : "0 years, 5 days, 4 hours, 14 minutes, 20 seconds, 13 milliseconds, 785 microseconds",
				"Max-Sessions" : "1000",
				"Event-Calling-Line-Number" : "75",
				"Event-Name" : "HEARTBEAT",
				"Session-Since-Startup" : "7515",
				"Event-Date-Local" : "2017-09-20 11:29:44",
				"Event-Calling-Function" : "send_heartbeat",
				"Session-Per-Sec-Max" : "26",
				"Event-Calling-File" : "switch_core.c",
				"Event-Info" : "System Ready",
				"Event-Date-GMT" : "Wed, 20 Sep 2017 11:29:44 GMT",
				"Event-Date-Timestamp" : "1505906984389049",
				"Session-Per-Sec" : "30",
				"Session-Peak-Max" : "26",
				"Session-Peak-FiveMin" : "1",
				"FreeSWITCH-IPv4" : "172.31.29.181",
				"FreeSWITCH-IPv6" : "::1",
				"Event-Sequence" : "1142811",
				"FreeSWITCH-Version" : "1.9.0+git~20170911T194756Z~2aea0c329b~64bit",
				"Session-Per-Sec-Last" : "0",
				"Idle-CPU" : "94.766667",
				"Core-UUID" : "a475b338-99e5-11e7-8b36-3bdaa2eeeccc",
				"Uptime-msec" : "447260013",
				"Session-Count" : "0",
				"Session-Per-Sec-FiveMin" : "1"
			},
			"type" : "Json"
		}
	]
}

**Comment by surendratiwari3** [comment]
@RichardKnop please add this pull request this will help to many programmer to store the result as json in mongosb.

**Comment by RichardKnop** [comment]
@surendratiwari3 Done

**Comment by RichardKnop** [comment]
Sorry. Had to revert this commit as it doesn't work. Integration tests are failing for some reason.

**Comment by surendratiwari3** [comment]
@RichardKnop can you suggest me to make some changes.as it is required by most of people.

**Comment by surendratiwari3** [comment]
i think i only made changes to backend mongo.might be integration test needs to be changed to get this scenario done.

**Pull request merged**
